#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     9,    44,    45,    21,    48,   126,    14,     3,    95,    50,
    23,     4,    28,     5,     7,    28,     3,    22,    52,    22,
     4,    14,     5,     7,    48,    96,    48,     8,    14,    50,
    24,    50,    48,     8,    51,    53,     8,    50,    52,    35,
    52,    36,   101,   106,    22,    99,    52,   104,   105,   107,
   108,   109,    37,    48,    51,    53,    51,    53,    50,    48,
    44,    45,    51,    53,    50,    71,    72,    52,    71,    72,
    38,    42,   106,    52,    39,   122,   104,   105,   107,   108,
   109,    48,    40,    51,    53,   110,    50,    48,    20,    51,
    53,    19,    50,    22,   116,    52,    71,    72,    63,    64,
   106,    52,   117,   113,   104,   105,   107,   108,   109,    48,
    28,    51,    53,   119,    50,   120,    18,    51,    53,    75,
    17,    16,    48,    52,    48,    14,    35,    50,    46,    50,
    48,    71,    72,    63,    64,    50,    52,    28,    52,    51,
    53,    54,   101,   106,    52,    99,    14,   104,   105,   107,
   108,   109,    51,    53,    51,    53,    11,    48,   133,    48,
    51,    53,    50,    48,    50,    48,    56,   nil,    50,   nil,
    50,    52,   nil,    52,   nil,   101,   106,    52,    99,    52,
   104,   105,   107,   108,   109,   nil,    48,    51,    53,    51,
    53,    50,    48,    51,    53,    51,    53,    50,    48,   nil,
    52,   nil,   nil,    50,    48,   nil,    52,   nil,   nil,    50,
    48,   nil,    52,   nil,   nil,    50,    51,    53,    52,   nil,
   nil,   nil,    51,    53,    52,    48,   nil,   nil,    51,    53,
    50,    48,   nil,    48,    51,    53,    50,    48,    50,    52,
    51,    53,    50,    48,   nil,    52,   nil,    52,    50,   nil,
   nil,    52,   nil,   nil,   nil,    51,    53,    52,   nil,   nil,
   nil,    51,    53,    51,    53,    48,   nil,    51,    53,   nil,
    50,   nil,   nil,    51,    53,   nil,   nil,   nil,   nil,    52,
    48,   nil,   nil,   nil,   nil,    50,    71,    72,    63,    64,
    61,    62,   nil,   nil,    52,    51,    53,   nil,   101,   106,
   nil,    99,   nil,   104,   105,   107,   108,   109,   nil,   nil,
    51,    53,    71,    72,    63,    64,    61,    62,    67,    68,
    69,    70,    65,    66,    60,    71,    72,    63,    64,    61,
    62,    67,    68,    69,    70,    65,    66,    60,   nil,   nil,
   nil,    97,    71,    72,    63,    64,    61,    62,    71,    72,
    63,    64,    61,    62,    76,    71,    72,    63,    64,    61,
    62,    67,    68,    69,    70,    65,    66,    60,   nil,   nil,
   nil,   nil,   nil,   115,    71,    72,    63,    64,    61,    62,
    67,    68,    69,    70,    65,    66,    60,   nil,   nil,   nil,
   nil,   nil,   127,    71,    72,    63,    64,    61,    62,    67,
    68,    69,    70,    65,    66,    60,   nil,   nil,   129,    71,
    72,    63,    64,    61,    62,    67,    68,    69,    70,    65,
    66,    60,   nil,   nil,    77,    71,    72,    63,    64,    61,
    62,    67,    68,    69,    70,    65,    66,    60,   nil,   nil,
   128,    71,    72,    63,    64,    61,    62,    67,    68,    69,
    70,    65,    66,    60,    71,    72,    63,    64,    61,    62,
    67,    68,    69,    70,    65,    66,    60,    71,    72,    63,
    64,    61,    62,    67,    68,    69,    70,    65,    66,    60,
    71,    72,    63,    64,    61,    62,    67,    68,    69,    70,
    65,    66,    60,    71,    72,    63,    64,    61,    62,    67,
    68,    69,    70,    65,    66,    60,    71,    72,    63,    64,
    61,    62,    71,    72,    63,    64,    61,    62,    71,    72,
    63,    64,    61,    62 ]

racc_action_check = [
     1,    74,    74,    12,    70,   118,   106,     0,    90,    70,
    14,     0,    17,     0,     0,    18,     1,    12,    70,   118,
     1,    20,     1,     1,   128,    90,   117,     0,    22,   128,
    15,   117,   116,    74,    70,    70,     1,   116,   128,    23,
   117,    25,   128,   128,    15,   128,   116,   128,   128,   128,
   128,   128,    26,   112,   128,   128,   117,   117,   112,   109,
    33,    33,   116,   116,   109,    82,    82,   112,    81,    81,
    28,    33,   112,   109,    29,   112,   112,   112,   112,   112,
   112,    99,    30,   112,   112,    94,    99,    96,    11,   109,
   109,     9,    96,    31,   104,    99,    80,    80,    80,    80,
    99,    96,   105,    99,    99,    99,    99,    99,    99,    42,
    75,    99,    99,   107,    42,   108,     8,    96,    96,    56,
     7,     6,    72,    42,   133,     5,    54,    72,    36,   133,
    71,    79,    79,    79,    79,    71,    72,    37,   133,    42,
    42,    40,   133,   133,    71,   133,     4,   133,   133,   133,
   133,   133,    72,    72,   133,   133,     3,   129,   130,    69,
    71,    71,   129,    68,    69,    67,    41,   nil,    68,   nil,
    67,   129,   nil,    69,   nil,   129,   129,    68,   129,    67,
   129,   129,   129,   129,   129,   nil,    66,   129,   129,    69,
    69,    66,    65,    68,    68,    67,    67,    65,    64,   nil,
    66,   nil,   nil,    64,    63,   nil,    65,   nil,   nil,    63,
    62,   nil,    64,   nil,   nil,    62,    66,    66,    63,   nil,
   nil,   nil,    65,    65,    62,    61,   nil,   nil,    64,    64,
    61,    60,   nil,    50,    63,    63,    60,    48,    50,    61,
    62,    62,    48,    38,   nil,    60,   nil,    50,    38,   nil,
   nil,    48,   nil,   nil,   nil,    61,    61,    38,   nil,   nil,
   nil,    60,    60,    50,    50,    44,   nil,    48,    48,   nil,
    44,   nil,   nil,    38,    38,   nil,   nil,   nil,   nil,    44,
    92,   nil,   nil,   nil,   nil,    92,    84,    84,    84,    84,
    84,    84,   nil,   nil,    92,    44,    44,   nil,    92,    92,
   nil,    92,   nil,    92,    92,    92,    92,    92,   nil,   nil,
    92,    92,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    58,    58,    58,    58,    58,
    58,    58,    58,    58,    58,    58,    58,    58,   nil,   nil,
   nil,    91,    85,    85,    85,    85,    85,    85,    86,    86,
    86,    86,    86,    86,    58,   103,   103,   103,   103,   103,
   103,   103,   103,   103,   103,   103,   103,   103,   nil,   nil,
   nil,   nil,   nil,   103,   121,   121,   121,   121,   121,   121,
   121,   121,   121,   121,   121,   121,   121,   nil,   nil,   nil,
   nil,   nil,   121,   125,   125,   125,   125,   125,   125,   125,
   125,   125,   125,   125,   125,   125,   nil,   nil,   125,    59,
    59,    59,    59,    59,    59,    59,    59,    59,    59,    59,
    59,    59,   nil,   nil,    59,   124,   124,   124,   124,   124,
   124,   124,   124,   124,   124,   124,   124,   124,   nil,   nil,
   124,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,   111,   111,   111,   111,   111,   111,
   111,   111,   111,   111,   111,   111,   111,    57,    57,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    57,    57,
    89,    89,    89,    89,    89,    89,    89,    89,    89,    89,
    89,    89,    89,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    83,    83,    83,    83,
    83,    83,    88,    88,    88,    88,    88,    88,    87,    87,
    87,    87,    87,    87 ]

racc_action_pointer = [
    -9,     0,   nil,   139,   129,   108,   100,   117,   113,    91,
   nil,    85,   -18,   nil,    -9,     9,   nil,    -5,    -2,   nil,
     4,   nil,    11,    22,   nil,    23,    17,   nil,    51,    56,
    64,    58,   nil,    56,   nil,   nil,   107,   120,   240,   nil,
   122,   130,   106,   nil,   262,   nil,   nil,   nil,   234,   438,
   230,   nil,   nil,   nil,   109,   nil,   116,   464,   322,   406,
   228,   222,   207,   201,   195,   189,   183,   162,   160,   156,
     1,   127,   119,   nil,    -3,    93,   nil,   nil,   490,   128,
    93,    65,    62,   503,   283,   339,   345,   515,   509,   477,
   -10,   309,   277,   nil,    67,   nil,    84,   nil,   nil,    78,
   nil,   nil,   nil,   352,    91,    99,   -11,    92,    94,    56,
   nil,   451,    50,   nil,   nil,   nil,    29,    23,   -16,   nil,
   nil,   371,   nil,   nil,   422,   390,   nil,   nil,    21,   154,
   127,   nil,   nil,   121,   nil ]

racc_action_default = [
   -66,   -66,    -2,   -66,   -66,   -66,   -66,   -66,   -66,   -66,
    -1,   -66,   -66,   -55,   -66,   -66,    -6,   -66,   -66,   135,
   -52,    -4,   -66,   -66,    -5,   -66,   -48,   -50,   -66,   -66,
   -66,   -53,   -54,   -57,   -62,   -65,   -66,   -66,   -66,   -47,
   -66,   -59,   -66,   -61,   -66,   -64,    -7,   -49,   -66,   -51,
   -66,   -39,   -40,   -41,   -66,   -56,   -66,   -58,   -66,   -66,
   -66,   -66,   -66,   -66,   -66,   -66,   -66,   -66,   -66,   -66,
   -66,   -44,   -66,   -36,   -45,   -66,   -63,   -24,   -25,   -26,
   -27,   -28,   -29,   -30,   -31,   -32,   -33,   -34,   -35,   -43,
   -66,   -66,   -66,   -46,   -66,   -37,   -66,   -38,    -3,   -66,
   -10,   -11,   -14,   -66,   -66,   -66,   -66,   -66,   -66,   -66,
   -60,   -42,   -66,    -9,   -13,   -15,   -66,   -66,   -66,   -19,
   -20,   -66,    -8,   -12,   -66,   -66,   -18,   -21,   -66,   -66,
   -22,   -17,   -16,   -66,   -23 ]

racc_goto_table = [
    12,    15,    49,    25,    29,    98,    57,    33,    58,   114,
     2,    10,    59,   112,    73,    92,    31,    93,    30,     1,
   132,    90,   123,    47,    78,    79,    80,    81,    82,    83,
    84,    85,    86,    87,    88,    89,    91,    32,    74,    41,
    55,   130,   131,   nil,   nil,   nil,   134,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   111,    94,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   121,   nil,   nil,   nil,   nil,   nil,   nil,
   124,   125,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   118 ]

racc_goto_check = [
     7,     7,    13,     9,     9,     6,    13,     4,    13,    11,
     2,     2,    13,    10,    13,     5,     7,     8,     3,     1,
    14,    15,    11,    17,    13,    13,    13,    13,    13,    13,
    13,    13,    13,    13,    13,    13,    13,    18,     4,    19,
    20,     6,     6,   nil,   nil,   nil,     6,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    13,     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,
    13,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     7 ]

racc_goto_pointer = [
   nil,    19,    10,    -2,   -16,   -59,   -87,    -4,   -57,   -14,
   -86,   -90,   nil,   -36,  -110,   -50,   nil,   -14,    15,     6,
    -1,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,   nil,
   nil,   100,   102,   103,   nil,   nil,    26,    27,    13,   nil,
   nil,    43,    34 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 38, :_reduce_1,
  1, 38, :_reduce_2,
  9, 39, :_reduce_3,
  3, 39, :_reduce_4,
  3, 39, :_reduce_5,
  2, 39, :_reduce_none,
  5, 39, :_reduce_7,
  3, 43, :_reduce_8,
  2, 43, :_reduce_9,
  1, 43, :_reduce_10,
  1, 43, :_reduce_11,
  2, 47, :_reduce_12,
  1, 47, :_reduce_13,
  1, 48, :_reduce_14,
  2, 49, :_reduce_15,
  6, 49, :_reduce_16,
  5, 49, :_reduce_17,
  3, 49, :_reduce_18,
  2, 49, :_reduce_19,
  2, 49, :_reduce_20,
  3, 49, :_reduce_21,
  0, 51, :_reduce_none,
  2, 51, :_reduce_23,
  3, 50, :_reduce_24,
  3, 50, :_reduce_25,
  3, 50, :_reduce_26,
  3, 50, :_reduce_27,
  3, 50, :_reduce_28,
  3, 50, :_reduce_29,
  3, 50, :_reduce_30,
  3, 50, :_reduce_31,
  3, 50, :_reduce_32,
  3, 50, :_reduce_33,
  3, 50, :_reduce_34,
  3, 50, :_reduce_35,
  2, 50, :_reduce_36,
  4, 50, :_reduce_37,
  4, 50, :_reduce_38,
  1, 50, :_reduce_none,
  1, 50, :_reduce_none,
  1, 50, :_reduce_none,
  3, 52, :_reduce_42,
  1, 52, :_reduce_43,
  0, 52, :_reduce_44,
  0, 42, :_reduce_none,
  1, 42, :_reduce_none,
  4, 45, :_reduce_47,
  1, 46, :_reduce_48,
  3, 53, :_reduce_49,
  1, 53, :_reduce_50,
  3, 54, :_reduce_51,
  0, 40, :_reduce_52,
  1, 40, :_reduce_none,
  3, 44, :_reduce_54,
  1, 44, :_reduce_55,
  5, 55, :_reduce_56,
  0, 56, :_reduce_none,
  2, 56, :_reduce_58,
  0, 57, :_reduce_none,
  4, 57, :_reduce_60,
  2, 41, :_reduce_61,
  1, 41, :_reduce_62,
  3, 58, :_reduce_63,
  1, 58, :_reduce_64,
  1, 59, :_reduce_none ]

racc_reduce_n = 66

racc_shift_n = 135

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  "(" => 3,
  "[" => 4,
  "*" => 5,
  "/" => 6,
  "+" => 7,
  "-" => 8,
  "<" => 9,
  ">" => 10,
  "<=" => 11,
  ">=" => 12,
  "==" => 13,
  "!=" => 14,
  "=" => 15,
  "function" => 16,
  :IDENT => 17,
  ")" => 18,
  ":" => 19,
  "const" => 20,
  ";" => 21,
  "var" => 22,
  "include_bin" => 23,
  "{" => 24,
  "}" => 25,
  "if" => 26,
  "while" => 27,
  "break" => 28,
  "continue" => 29,
  "return" => 30,
  "else" => 31,
  "]" => 32,
  :NUMBER => 33,
  :STRING => 34,
  "," => 35,
  "options" => 36 }

racc_nt_base = 37

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "\"(\"",
  "\"[\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\"=\"",
  "\"function\"",
  "IDENT",
  "\")\"",
  "\":\"",
  "\"const\"",
  "\";\"",
  "\"var\"",
  "\"include_bin\"",
  "\"{\"",
  "\"}\"",
  "\"if\"",
  "\"while\"",
  "\"break\"",
  "\"continue\"",
  "\"return\"",
  "\"else\"",
  "\"]\"",
  "NUMBER",
  "STRING",
  "\",\"",
  "\"options\"",
  "$start",
  "program",
  "decl",
  "var_decl_list_if",
  "type_decl",
  "options_if",
  "block",
  "var_decl_list",
  "options",
  "option_list",
  "statement_list",
  "statement_i",
  "statement",
  "exp",
  "else_block",
  "exp_list",
  "option_list_sub",
  "option",
  "var_decl",
  "var_init",
  "var_option",
  "type_modifier",
  "basic_type" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_1(val, _values, result)
     result = val[0] + [val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_2(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_3(val, _values, result)
     result = [:function, val[1], val[3], val[6], val[8]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_4(val, _values, result)
     result = [:const, val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_5(val, _values, result)
     result = [:var, val[1]] 
    result
  end
.,.,

# reduce 6 omitted

module_eval(<<'.,.,', 'parser.y', 21)
  def _reduce_7(val, _values, result)
     result = [:include_bin, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_8(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_9(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_10(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_11(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_12(val, _values, result)
     result = val[0] + [val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_13(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_14(val, _values, result)
     info(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_15(val, _values, result)
     result = [:exp, val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_16(val, _values, result)
     result = [:if, val[2], val[4], val[5]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_17(val, _values, result)
     result = [:while, val[2], val[4]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_18(val, _values, result)
     result = [:var, val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_19(val, _values, result)
     result = [:break] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_20(val, _values, result)
     result = [:continue] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_21(val, _values, result)
     result = [:return, val[1]] 
    result
  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_23(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 46)
  def _reduce_24(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_25(val, _values, result)
     result = [:load, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_26(val, _values, result)
     result = [:add, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_27(val, _values, result)
     result = [:sub, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_28(val, _values, result)
     result = [:mul, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_29(val, _values, result)
     result = [:div, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_30(val, _values, result)
     result = [:eq, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_31(val, _values, result)
     result = [:ne, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_32(val, _values, result)
     result = [:lt, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_33(val, _values, result)
     result = [:gt, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_34(val, _values, result)
     result = [:le, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_35(val, _values, result)
     result = [:ge, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_36(val, _values, result)
     result = [:uminus, val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_37(val, _values, result)
     result = [:call, val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_38(val, _values, result)
     result = [:index, val[0], val[2]] 
    result
  end
.,.,

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_42(val, _values, result)
     result = val[0] + [val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_43(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_44(val, _values, result)
     result = [] 
    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_47(val, _values, result)
     result = [:options, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_48(val, _values, result)
     result = Hash[ *val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_49(val, _values, result)
     result = val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_50(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_51(val, _values, result)
     result = [val[0],val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_52(val, _values, result)
    result = [] 
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.y', 82)
  def _reduce_54(val, _values, result)
     result = val[0]+[val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_55(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_56(val, _values, result)
     result = [val[0], val[2], val[3], val[4]] 
    result
  end
.,.,

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.y', 87)
  def _reduce_58(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 59 omitted

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_60(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_61(val, _values, result)
     result = [val[1], val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_62(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_63(val, _values, result)
     result = [:array, val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 94)
  def _reduce_64(val, _values, result)
     result = :pointer 
    result
  end
.,.,

# reduce 65 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
