BEGIN;

CREATE TABLE projects (
	id SERIAL PRIMARY KEY,
	url VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	UNIQUE INDEX ( url )
);

CREATE TABLE urls (
	id SERIAL PRIMARY KEY,
	project_id INTEGER,
	url VARCHAR(255) NOT NULL,
	expire_at DATETIME NOT NULL DEFAULT 0,
	status VARCHAR(1) NOT NULL DEFAULT '',
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	UNIQUE INDEX ( project_id, url ),
	INDEX ( url ),
	INDEX ( status, expire_at ),
	INDEX ( project_id )
);

-- CREATE INDEX urls_status_expire_at ON urls ( status, expire_at );


CREATE TABLE images (
	id SERIAL PRIMARY KEY,
	project_id INTEGER NOT NULL,
	url VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(100) NOT NULL,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	INDEX ( project_id )
);

COMMIT;
