all:
	GOPATH=/usr/local/Cellar/go/1.0.3:~/work/shogi go run hello.go hoge.ki2

test_ab:
	GOPATH=/usr/local/Cellar/go/1.0.3:~/work/shogi go run test_ab.go

net:
	GOPATH=/usr/local/Cellar/go/1.0.3:~/work/shogi go run net.go

cli:
	GOPATH=/usr/local/Cellar/go/1.0.3:~/work/shogi go run cli.go

test:
	GOPATH=`pwd` go test shogi shogi/kifu



