
all:
	GOPATH=`pwd` go run hello.go hoge.ki2

test_ab:
	GOPATH=`pwd` go run test_ab.go

net:
	GOPATH=`pwd` go run net.go

cli:
	GOPATH=`pwd` go run cli.go

test:
	GOPATH=`pwd` go test shogi shogi/kifu

kifutest:
	GOPATH=`pwd` go run kifutest.go misc


