# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Master.I18nMessage" do
    optional :id, :string, 1
    optional :text, :string, 2
    optional :tag, :string, 3
    optional :variant, :string, 4
    optional :lang, :enum, 5, "Master.LangType"
  end
  add_message "Master.SceneSummary" do
    optional :id, :int32, 1
    optional :original_filename, :string, 2
    optional :chapter, :int32, 3
    optional :scene, :int32, 4
    optional :subscene, :int32, 5
    optional :scene_name, :string, 6
    optional :desc, :string, 7
  end
  add_message "Master.ChapterDesc" do
    optional :chapter, :int32, 1
    optional :name, :string, 2
  end
  add_message "Master.SceneDesc" do
    optional :chapter, :int32, 1
    optional :scene, :int32, 2
    optional :name, :string, 3
  end
  add_message "Master.DebugMenuInfo" do
    optional :name, :string, 1
    optional :action, :string, 2
    optional :shortcut, :string, 4
  end
  add_message "Master.FastTravelDesc" do
    optional :id, :int32, 1
    optional :permanent, :bool, 2
    optional :order, :int32, 3
    optional :parent, :int32, 4
    optional :from, :int32, 5
    optional :door, :int32, 6
    optional :start, :int32, 7
    optional :flag1a, :int32, 8
    optional :flag1b, :int32, 9
    optional :flag2a, :int32, 10
    optional :flag2b, :int32, 11
    optional :flag3a, :int32, 12
    optional :flag3b, :int32, 13
    optional :flag4a, :int32, 14
    optional :flag4b, :int32, 15
    optional :flag5a, :int32, 16
    optional :flag5b, :int32, 17
    optional :flag6a, :int32, 18
    optional :flag6b, :int32, 19
  end
  add_message "Master.CharacterGallery" do
    optional :id, :int32, 1
    optional :character_id, :int32, 2
    optional :chapter, :int32, 3
    optional :image_name, :string, 4
    optional :voice_message_id, :int32, 5
    optional :voice_name, :string, 6
    optional :sort_id, :int32, 7
  end
  add_message "Master.CharacterGalleryVoiceMessage" do
    optional :id, :int32, 1
    optional :ja, :string, 2
    optional :en, :string, 3
    optional :zh_tw, :string, 4
  end
  add_message "Master.Character" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :name_en, :string, 3
    optional :name_zh_tw, :string, 4
  end
  add_message "Master.ShinmitsuGallery" do
    optional :id, :int32, 1
    optional :character_id, :int32, 2
    repeated :script_ids, :int32, 3
    optional :image_y, :int32, 4
    optional :image_x, :int32, 5
  end
  add_message "Master.SuperArtGallery" do
    optional :id, :int32, 1
    optional :message_id, :int32, 2
    optional :image_name, :string, 3
    optional :price, :int32, 4
  end
  add_message "Master.SuperArtGalleryMessage" do
    optional :id, :int32, 1
    optional :ja, :string, 2
    optional :en, :string, 3
    optional :zh_tw, :string, 4
  end
  add_enum "Master.LangType" do
    value :Ja, 0
    value :ZhTw, 1
    value :En, 2
  end
  add_enum "Master.PlatformType" do
    value :Switch, 0
    value :Steam, 1
    value :Wsa, 2
    value :Ps4, 3
    value :Android, 5
    value :Ios, 6
  end
end

module Master
  I18nMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.I18nMessage").msgclass
  SceneSummary = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SceneSummary").msgclass
  ChapterDesc = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.ChapterDesc").msgclass
  SceneDesc = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SceneDesc").msgclass
  DebugMenuInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.DebugMenuInfo").msgclass
  FastTravelDesc = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.FastTravelDesc").msgclass
  CharacterGallery = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.CharacterGallery").msgclass
  CharacterGalleryVoiceMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.CharacterGalleryVoiceMessage").msgclass
  Character = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.Character").msgclass
  ShinmitsuGallery = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.ShinmitsuGallery").msgclass
  SuperArtGallery = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SuperArtGallery").msgclass
  SuperArtGalleryMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SuperArtGalleryMessage").msgclass
  LangType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.LangType").enummodule
  PlatformType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.PlatformType").enummodule
end
