// Generated by CoffeeScript 1.3.3
(function() {

  enchant();

  window.onload = function() {
    var game;
    game = new Game(320, 320);
    game.preload('bear.gif');
    game.onload = function() {
      var pad, scene, spr;
      scene = new Scene();
      scene.backgroundColor = '#ddd';
      game.pushScene(scene);
      spr = new Sprite(20, 30);
      spr.image = game.assets['bear.gif'];
      spr.count = 0;
      spr.scaleX = 2;
      spr.scaleY = 2;
      spr.addEventListener('enterframe', function() {
        var x, y;
        spr.count += 1;
        x = spr.x;
        y = spr.y;
        if (game.input.up) {
          y -= 4;
        }
        if (game.input.down) {
          y += 4;
        }
        if (game.input.left) {
          x -= 4;
        }
        if (game.input.right) {
          x += 4;
        }
        if (game.input.up || game.input.down || game.input.left || game.input.right) {
          spr.frame = (spr.count / 4 | 0) % 3;
        } else {
          spr.frame = 0;
        }
        return spr.moveTo(x, y);
      });
      scene.addChild(spr);
      pad = new enchant.ui.Pad();
      pad.moveTo(20, 200);
      return scene.addChild(pad);
    };
    return game.start();
  };

}).call(this);
