# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_base.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Game.DrsVector2" do
    optional :x, :float, 1
    optional :y, :float, 2
  end
  add_message "Game.DrsVector3" do
    optional :x, :float, 1
    optional :y, :float, 2
    optional :z, :float, 3
  end
  add_message "Game.DrsMatrix4" do
    repeated :val, :float, 1
  end
  add_message "Game.DrsColor" do
    optional :r, :int32, 1
    optional :g, :int32, 2
    optional :b, :int32, 3
    optional :a, :int32, 4
  end
  add_message "Game.DrFade" do
    optional :sync, :int32, 1
    optional :mode, :enum, 2, "Game.DrFade.Mode"
  end
  add_enum "Game.DrFade.Mode" do
    value :FadeModeIn, 0
    value :FadeModeOut, 1
    value :FadeModeMax, 2
  end
end

module Game
  DrsVector2 = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game.DrsVector2").msgclass
  DrsVector3 = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game.DrsVector3").msgclass
  DrsMatrix4 = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game.DrsMatrix4").msgclass
  DrsColor = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game.DrsColor").msgclass
  DrFade = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game.DrFade").msgclass
  DrFade::Mode = Google::Protobuf::DescriptorPool.generated_pool.lookup("Game.DrFade.Mode").enummodule
end
