task :default do
  sh 'racc parse.y'
  sh 'ruby codegen.rb test.txt'
end

task :test => :build do
  sh 'dotnet run --project TestProj'
end

desc 'Generate test .proto'
task :proto do
  sh 'protoc --csharp_out=. test.proto'
end
