    ;; this file is generated by fc command

    ;; options
<%= options_asm %>

    ;; interrupt vector
	.bank 1
	.org $FFFA
	.dw __interrupt
	.dw __start
	.dw 0

    ;; 
	.bank 0
__reg = 0                       ; 汎用レジスタ

	.org $8000
__start:
	sei
	ldx #255
	txs
	jsr __init
.loop:
    jmp .loop

__interrupt:
    pha
    txa
    pha
    tya
    pha
    jsr _Vinterrupt
    pla
    tay
    pla
    tax
    pla
    rti

<%= code_asm %>
<%= chr_asm %>
