    ;; this file is generated by fc command

    ;; options
@OPTIONS
	;; interrupt vector
	.bank 2
	.org $0000
	.incbin "character.chr"
	.incbin "character.chr"

    ;; interrupt vector
	.bank 1
	.org $FFFA
	.dw __interrupt
	.dw __start
	.dw 0

        ;; 
	.bank 0
__reg = 0                       ; 汎用レジスタ

	.org $8000
__start:
	sei
	ldx #255
	txs
	jsr __init
.loop:
    jmp .loop

__interrupt:
    pha
    txa
    pha
    tya
    pha
    jsr _Vinterrupt
    pla
    tay
    pla
    tax
    pla
    rti

@CODE
